In [11]:
import Bio
import pandas as pd
import numpy as np
import seaborn as sns
import os
import logomaker
import matplotlib.pyplot as plt
import scipy.stats as sp
from scipy.stats import ttest_ind
from scipy.stats import t
plt.rcParams['savefig.dpi'] = 300
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Data import IUPACData

# COMPILING Q/QQ ENDINGS

In this set of cells, I am parsing through the fasta file of the entire yeast proteome to find proteins that end in Q, QQ or QQQ, as well as all proteins that end in duplicate amino acids generally. I used the file: uniprotkb_proteome_UP000002311_2024_09_20.fasta, downloaded from https://www.uniprot.org/uniprotkb?query=proteome:UP000002311.

In [12]:
records = list(SeqIO.parse("uniprotkb_proteome_UP000002311_2024_09_20.fasta", "fasta"))
#obtained from https://www.uniprot.org/uniprotkb?query=proteome:UP000002311
len(records)

6060

In [3]:
print(records[1:3])
#checking file to see how sequence is annotated

[SeqRecord(seq=Seq('MSDAAPSLSNLFYDPTYNPGQSTINYTSIYGNGSTITFDELQGLVNSTVTQAIM...NNL'), id='sp|D6VTK4|STE2_YEAST', name='sp|D6VTK4|STE2_YEAST', description='sp|D6VTK4|STE2_YEAST Pheromone alpha factor receptor OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=STE2 PE=1 SV=2', dbxrefs=[]), SeqRecord(seq=Seq('MSYTDNPPQTKRALSLDDLVNHDENEKVKLQKLSEAANGSRPFAENLESDINQT...KVM'), id='sp|O13297|CET1_YEAST', name='sp|O13297|CET1_YEAST', description='sp|O13297|CET1_YEAST mRNA-capping enzyme subunit beta OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CET1 PE=1 SV=2', dbxrefs=[])]

In [4]:
endsinQ = [record for record in records if str(record.seq).endswith('Q')]
endsinQQ = [record for record in records if str(record.seq).endswith('QQ')]
endsinQQQ = [record for record in records if str(record.seq).endswith('QQQ')]

In [5]:
endsinQQQ
#only one yeast protein ends in QQQ (PUB1) so I opted not to save that one

[SeqRecord(seq=Seq('MSENNEEQHQQQQQQQPVAVETPSAVEAPASADPSSEQSVAVEGNSEQAEDNQG...QQQ'), id='sp|P32588|PUB1_YEAST', name='sp|P32588|PUB1_YEAST', description='sp|P32588|PUB1_YEAST Nuclear and cytoplasmic polyadenylated RNA-binding protein PUB1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=PUB1 PE=1 SV=4', dbxrefs=[])]

In [6]:
#saving Q endings
Q_endings = {
    "id": [record.id for record in endsinQ],
    "name": [record.name for record in endsinQ],
    "description": [record.description for record in endsinQ],
    "sequence": [str(record.seq) for record in endsinQ]
}
df = pd.DataFrame(Q_endings)
df

df.to_csv('filtered_seqrecords_endsinQ.csv', index=False)

In [8]:
#saving QQ endings
QQ_endings = {
    "id": [record.id for record in endsinQQ],
    "name": [record.name for record in endsinQQ],
    "description": [record.description for record in endsinQQ],
    "sequence": [str(record.seq) for record in endsinQQ]
}
df = pd.DataFrame(QQ_endings)
df

df.to_csv('filtered_seqrecords_endsinQQ.csv', index=False)

# COMPILING ALL DUPLICATE AA ENDINGS

In [17]:
# Get all amino acids
amino_acids = list(IUPACData.protein_letters)  # Standard one-letter codes for amino acids

# Generate all duplicates and triplicates
duplicates = [aa * 2 for aa in amino_acids]
triplicates = [aa * 3 for aa in amino_acids]

# Function to filter by suffix
def filter_by_suffix(records, suffix):
    """Filter sequences that end with a specific suffix."""
    return [record for record in records if str(record.seq).endswith(suffix)]

# Filter for duplicates
filtered_duplicates = {suffix: filter_by_suffix(records, suffix) for suffix in duplicates}

# Filter for triplicates
filtered_triplicates = {suffix: filter_by_suffix(records, suffix) for suffix in triplicates}

In [18]:
filtered_duplicates

{'AA': [SeqRecord(seq=Seq('MARYGATSTNPAKSASARGSYLRVSFKNTRETAQAINGWELTKAQKYLEQVLDH...IAA'), id='sp|P05740|RL17A_YEAST', name='sp|P05740|RL17A_YEAST', description='sp|P05740|RL17A_YEAST Large ribosomal subunit protein uL22A OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RPL17A PE=1 SV=4', dbxrefs=[]),
  SeqRecord(seq=Seq('MTNEKVWIEKLDNPTLSVLPHDFLRPQQEPYTKQATYSLQLPQLDVPHDSFSNK...AAA'), id='sp|P07702|LYS2_YEAST', name='sp|P07702|LYS2_YEAST', description='sp|P07702|LYS2_YEAST L-2-aminoadipate reductase OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=LYS2 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MDISKPVGSEITSVDFGILTAKEIRNLSAKQITNPTVLDNLGHPVSGGLYDLAL...NAA'), id='sp|P10964|RPA1_YEAST', name='sp|P10964|RPA1_YEAST', description='sp|P10964|RPA1_YEAST DNA-directed RNA polymerase I subunit RPA190 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RPA190 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MSATSTATSTSASQLHLNSTPVTHCLSDIVKKEDWSDFKFAPIRESTVSRAMTS...FAA'), id='sp|P32318|THI4_YEAST', name='sp|P32318|THI4_YEAST', description='sp|P32318|THI4_YEAST Thiamine thiazole synthase OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=THI4 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MMFNIYLFVTFFSTILAGSLSDLEIGIIKRIPVEDCLIKAMPGDKVKVHYTGSL...SAA'), id='sp|P32472|FKBP2_YEAST', name='sp|P32472|FKBP2_YEAST', description='sp|P32472|FKBP2_YEAST Peptidyl-prolyl cis-trans isomerase FPR2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=FPR2 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MTIIVASLFLPYTPQFEADVTNSDTAKLVESSMIKVDCNNQELSNNKQERSSSV...TAA'), id='sp|P38426|TPS3_YEAST', name='sp|P38426|TPS3_YEAST', description='sp|P38426|TPS3_YEAST Trehalose synthase complex regulatory subunit TPS3 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=TPS3 PE=1 SV=3', dbxrefs=[]),
  SeqRecord(seq=Seq('MASINLIKSLKLYKEKIWSFDFSQGILATGSTDRKIKLVSVKYDDFTLIDVLDE...KAA'), id='sp|Q05583|CIAO1_YEAST', name='sp|Q05583|CIAO1_YEAST', description='sp|Q05583|CIAO1_YEAST Cytosolic iron-sulfur protein assembly protein 1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CIA1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSDHSPISNKENHLLPSDSSRSSSSDMHSTGTTGTTGVEPVDFTGEGAKYTTAT...YAA'), id='sp|Q07824|TPO1_YEAST', name='sp|Q07824|TPO1_YEAST', description='sp|Q07824|TPO1_YEAST Polyamine transporter 1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=TPO1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSTYDEIEIEDMTFEPENQMFTYPCPCGDRFQIYLDDMFEGEKVAVCPSCSLMI...AAA'), id='sp|Q3E840|DPH3_YEAST', name='sp|Q3E840|DPH3_YEAST', description='sp|Q3E840|DPH3_YEAST Diphthamide biosynthesis protein 3 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=KTI11 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSFGSKVSRALRFLEIPVKDRASVSFLKNPDLQPIKSANQTWGFWSNFAYWGVM...KAA'), id='sp|Q05998|THI7_YEAST', name='sp|Q05998|THI7_YEAST', description='sp|Q05998|THI7_YEAST Thiamine transporter OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=THI7 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MYIKAEQKPQQFERKNEKLDRNKNQQLPDLETDFKGYRVNSDLYNKERDGSTEE...AAA'), id='sp|P40036|GIP2_YEAST', name='sp|P40036|GIP2_YEAST', description='sp|P40036|GIP2_YEAST GLC7-interacting protein 2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=GIP2 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MVDLSTALIHGDDKDNRVTDVAPPINVSTTFRYDDDDLIPWTERENLDFMEKKP...DAA'), id='sp|P38716|YHR2_YEAST', name='sp|P38716|YHR2_YEAST', description='sp|P38716|YHR2_YEAST Uncharacterized trans-sulfuration enzyme YHR112C OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YHR112C PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MFFFPKLRKLIGSTVIDHDTKNSSGKEEIMSNSRLALVIINHAFDKVLSLTWHC...KAA'), id='sp|Q05611|BSC2_YEAST', name='sp|Q05611|BSC2_YEAST', description='sp|Q05611|BSC2_YEAST Bypass of stop codon protein 2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=BSC2 PE=1 SV=1', dbxrefs=[])],
 'CC': [SeqRecord(seq=Seq('MNSEYDYLFKLLLIGNSGVGKSCLLLRFSDDTYTNDYISTIGVDFKIKTVELDG...GCC'), id='sp|P01123|YPT1_YEAST', name='sp|P01123|YPT1_YEAST', description='sp|P01123|YPT1_YEAST GTP-binding protein YPT1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YPT1 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MSGLRTVSASSGNGKSYDSIMKILLIGDSGVGKSCLLVRFVEDKFNPSFITTIG...NCC'), id='sp|P07560|SEC4_YEAST', name='sp|P07560|SEC4_YEAST', description='sp|P07560|SEC4_YEAST Ras-related protein SEC4 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=SEC4 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSMPIASTTLAVNNLTNINGNANFNVQANKQLHHQAVDSPARSSMTATTAANSN...GCC'), id='sp|P23291|KC11_YEAST', name='sp|P23291|KC11_YEAST', description='sp|P23291|KC11_YEAST Casein kinase I homolog 1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YCK1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSQVQSPLTATNSGLAVNNNTMNSQMPNRSNVRLVNGTLPPSLHVSSNLNHNTG...GCC'), id='sp|P23292|KC12_YEAST', name='sp|P23292|KC12_YEAST', description='sp|P23292|KC12_YEAST Casein kinase I homolog 2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YCK2 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSSEDYGYDYDLLFKIVLIGDSGVGKSNLLSRFTKNEFNMDSKSTIGVEFATRT...NCC'), id='sp|P38555|YPT31_YEAST', name='sp|P38555|YPT31_YEAST', description='sp|P38555|YPT31_YEAST GTP-binding protein YPT31/YPT8 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YPT31 PE=1 SV=3', dbxrefs=[]),
  SeqRecord(seq=Seq('MSQRSSQHIVGIHYAVGPKIGEGSFGVIFEGENILHSCQAQTGSKRDSSIIMAN...CCC'), id='sp|P39962|KC13_YEAST', name='sp|P39962|KC13_YEAST', description='sp|P39962|KC13_YEAST Casein kinase I homolog 3 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YCK3 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MSNEDYGYDYDYLFKIVLIGDSGVGKSNLLSRFTTDEFNIESKSTIGVEFATRT...NCC'), id='sp|P51996|YPT32_YEAST', name='sp|P51996|YPT32_YEAST', description='sp|P51996|YPT32_YEAST GTP-binding protein YPT32/YPT11 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YPT32 PE=1 SV=3', dbxrefs=[]),
  SeqRecord(seq=Seq('MVKKVNNPLKIDYQNGIIENRLLQIRNFKDVNTPKLINVWSIRIDPRDSKKVIE...VCC'), id='sp|Q9URQ3|TAD3_YEAST', name='sp|Q9URQ3|TAD3_YEAST', description='sp|Q9URQ3|TAD3_YEAST tRNA-specific adenosine deaminase subunit TAD3 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=TAD3 PE=1 SV=1', dbxrefs=[])],
 'DD': [SeqRecord(seq=Seq('MNPGGEQTIMEQPAQQQQQQQQQQQQQQQQAAVPQQPLDPLTQSTAETWLSIAS...YDD'), id='sp|P14922|CYC8_YEAST', name='sp|P14922|CYC8_YEAST', description='sp|P14922|CYC8_YEAST General transcriptional corepressor CYC8 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CYC8 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MVKRTVATNGDASGAHRAKKMSKTHASHIINAQEDYKHMYLSVQPLDIFCWGTG...MDD'), id='sp|P21827|RCC1_YEAST', name='sp|P21827|RCC1_YEAST', description='sp|P21827|RCC1_YEAST Guanine nucleotide exchange factor SRM1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=SRM1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MVRLKSRYILFEIIFPPTDTNVEESVSKADILLSHHRASPADVSIKSILQEIRR...EDD'), id='sp|P28005|POP5_YEAST', name='sp|P28005|POP5_YEAST', description='sp|P28005|POP5_YEAST Ribonuclease P/MRP protein subunit POP5 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=POP5 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MEGILDFSNDLDIALLDQVVSTFYQGSGVQQKQAQEILTKFQDNPDAWQKADQI...LDD'), id='sp|P30822|XPO1_YEAST', name='sp|P30822|XPO1_YEAST', description='sp|P30822|XPO1_YEAST Exportin-1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CRM1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MFRQCAKRYASSLPPNALKPAFGPPDKVAAQKFKESLMATEKHAKDTSNMWVKI...HDD'), id='sp|P32799|COX13_YEAST', name='sp|P32799|COX13_YEAST', description='sp|P32799|COX13_YEAST Cytochrome c oxidase subunit 13, mitochondrial OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=COX13 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSRIDSDLQKALKKACSVEETAPKRKHVRACIVYTWDHQSSKAVFTTLKTLPLA...DDD'), id='sp|P33338|SLA2_YEAST', name='sp|P33338|SLA2_YEAST', description='sp|P33338|SLA2_YEAST Protein SLA2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=SLA2 PE=1 SV=5', dbxrefs=[]),
  SeqRecord(seq=Seq('MSQSNPILRGLAITTAIAALSATGYAIYFDYQRRNSPQFRKVLRQRAKEQAKME...IDD'), id='sp|P35180|TOM20_YEAST', name='sp|P35180|TOM20_YEAST', description='sp|P35180|TOM20_YEAST Mitochondrial import receptor subunit TOM20 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=TOM20 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MLRTTRLWTTRMPTVSKLFLRNSSGNALNKNKLPFLYSSQGPQAVRYTSQHEWI...HDD'), id='sp|P39726|GCSH_YEAST', name='sp|P39726|GCSH_YEAST', description='sp|P39726|GCSH_YEAST Glycine cleavage system H protein, mitochondrial OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=GCV3 PE=1 SV=3', dbxrefs=[]),
  SeqRecord(seq=Seq('MSELQSQPKKIAVVTGASGGIGYEVTKELARNGYLVYACARRLEPMAQLAIQFG...KDD'), id='sp|P40471|AYR1_YEAST', name='sp|P40471|AYR1_YEAST', description='sp|P40471|AYR1_YEAST NADPH-dependent 1-acyldihydroxyacetone phosphate reductase OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=AYR1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MARSLSQSLTATTQKLKGKKNGGKGKNKPSAKIKKTQKEMLYGILNERNIRQIQ...IDD'), id='sp|P40963|SAS2_YEAST', name='sp|P40963|SAS2_YEAST', description='sp|P40963|SAS2_YEAST Histone acetyltransferase SAS2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=SAS2 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSADLQQGTTNAADFSLTVLRARIALLATAIGGPDYTSQIDPPPYKLGDDCLAC...SDD'), id='sp|P53840|TOF1_YEAST', name='sp|P53840|TOF1_YEAST', description='sp|P53840|TOF1_YEAST Topoisomerase 1-associated factor 1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=TOF1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MESLFPNKGEIIRELLKDPLILKNDSKRSNGSELELDSSDLLQREAILANELNI...LDD'), id='sp|P53847|DSL1_YEAST', name='sp|P53847|DSL1_YEAST', description='sp|P53847|DSL1_YEAST Protein transport protein DSL1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=DSL1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MVVVGKSEVRNVSMSRPKKKSLIAILSTCVLFFLVFIIGAKFQYVSVFSKFLDD...KDD'), id='sp|Q04119|PPN1_YEAST', name='sp|Q04119|PPN1_YEAST', description='sp|Q04119|PPN1_YEAST Endopolyphosphatase OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=PPN1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSFRDVLERGDEFLEAYPRRSPLWRFLSYSTSLLTFGVSKLLLFTCYNVKLNGF...KDD'), id='sp|Q06510|TAZ_YEAST', name='sp|Q06510|TAZ_YEAST', description='sp|Q06510|TAZ_YEAST Tafazzin OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=TAZ1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MAKSKSSQGASGARRKPAPSLYQHISSFKPQFSTRVDDVLHFSKTLTWRSEIIP...YDD'), id='sp|Q12206|WTM2_YEAST', name='sp|Q12206|WTM2_YEAST', description='sp|Q12206|WTM2_YEAST Transcriptional modulator WTM2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=WTM2 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSLTPLCEDLPQFLQNYLPNAGQTENTIVPFVTLTYAQSLDARVSRGPGVRTTI...ADD'), id='sp|P33312|RIB7_YEAST', name='sp|P33312|RIB7_YEAST', description="sp|P33312|RIB7_YEAST 2,5-diamino-6-ribosylamino-4(3H)-pyrimidinone 5'-phosphate reductase OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RIB7 PE=1 SV=1", dbxrefs=[]),
  SeqRecord(seq=Seq('MMAFENTSKRPPQDFVAPIDQKKRKVQFSDSTGLVTLQPEEIKDEVFSAAMYSR...SDD'), id='sp|P36070|RRN3_YEAST', name='sp|P36070|RRN3_YEAST', description='sp|P36070|RRN3_YEAST RNA polymerase I-specific transcription initiation factor RRN3 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RRN3 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MEEVFRFYSNSRNIFIHKSLSLKPSTIDDPKSGYGLFVEPSKFKNDELKSETIQ...QDD'), id='sp|P38818|CTM1_YEAST', name='sp|P38818|CTM1_YEAST', description='sp|P38818|CTM1_YEAST Cytochrome c lysine N-methyltransferase 1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CTM1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MFSLSSLSSSGGHSEQKERERISYFDIRINSPYKDIILIQGSPLELSSIPLSGN...DDD'), id='sp|P53244|ART5_YEAST', name='sp|P53244|ART5_YEAST', description='sp|P53244|ART5_YEAST Arrestin-related trafficking adapter 5 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=ART5 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MTTQIRSPQGLPYPIQIDKLIPSVGSYLHEGDRLLVYKFWYLVERASDTGDDDN...LDD'), id='sp|Q03254|FCP1_YEAST', name='sp|Q03254|FCP1_YEAST', description='sp|Q03254|FCP1_YEAST RNA polymerase II subunit A C-terminal domain phosphatase OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=FCP1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MGNIITDTIIITSDKCDIVDNDNVERIQVWLSKNILRKFQINENEPLQLIILKR...DDD'), id='sp|P36054|RCN1_YEAST', name='sp|P36054|RCN1_YEAST', description='sp|P36054|RCN1_YEAST Calcipressin-like protein OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RCN1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MVAEFQIASAQSSALTSTEEEHCSINSDKAAKLDLELTSERKNDGKQSHEVTFN...WDD'), id='sp|P38776|YHK8_YEAST', name='sp|P38776|YHK8_YEAST', description='sp|P38776|YHK8_YEAST Probable drug/proton antiporter YHK8 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YHK8 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MPLNIIGTALLDGTDKIPYYQTIKKVAPYVLATGAIKYWSRGPSNTWERKLHGK...KDD'), id='sp|P53878|YNS1_YEAST', name='sp|P53878|YNS1_YEAST', description='sp|P53878|YNS1_YEAST Uncharacterized oxidoreductase YNL181W OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YNL181W PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MEDTIRPLNYADIETSGPINLLETTNNLKSSLKKFSQKAKGSHISRERIHHFRK...SDD'), id='sp|P33199|YGB5_YEAST', name='sp|P33199|YGB5_YEAST', description='sp|P33199|YGB5_YEAST Uncharacterized protein YGL015C OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YGL015C PE=4 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MRRLYRHLASFFLLPSCPGNTIQSITSYPANALLRSFRHVSTETPVRNRVHNRD...MDD'), id='sp|Q3E763|YD246_YEAST', name='sp|Q3E763|YD246_YEAST', description='sp|Q3E763|YD246_YEAST Uncharacterized protein YDR246W-A OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YDR246W-A PE=3 SV=1', dbxrefs=[])],
 'EE': [SeqRecord(seq=Seq('MPRAPRTYSKTYSTPKRPYESSRLDAELKLAGEFGLKNKKEIYRISFQLSKIRR...DEE'), id='sp|O13516|RS9A_YEAST', name='sp|O13516|RS9A_YEAST', description='sp|O13516|RS9A_YEAST Small ribosomal subunit protein uS4A OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RPS9A PE=1 SV=3', dbxrefs=[]),
  SeqRecord(seq=Seq('MPRAPRTYSKTYSTPKRPYESSRLDAELKLAGEFGLKNKREIYRISFQLSKIRR...DEE'), id='sp|P05755|RS9B_YEAST', name='sp|P05755|RS9B_YEAST', description='sp|P05755|RS9B_YEAST Small ribosomal subunit protein uS4B OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RPS9B PE=1 SV=4', dbxrefs=[]),
  SeqRecord(seq=Seq('MNSSNNNDSSSSNSNMNNSLSPTLVTHSDASMGSGRASPDNSHMGRGIWNPSYV...VEE'), id='sp|P14680|YAK1_YEAST', name='sp|P14680|YAK1_YEAST', description='sp|P14680|YAK1_YEAST Dual specificity protein kinase YAK1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=YAK1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MIRRAPTTLQLSHDDVTSLIDDLNEQKLKQQLNIEKTKYFQGKNGGSLHSNTDF...REE'), id='sp|P14724|CDC26_YEAST', name='sp|P14724|CDC26_YEAST', description='sp|P14724|CDC26_YEAST Anaphase-promoting complex subunit CDC26 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CDC26 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MLEAKFEEASLFKRIIDGFKDCVQLVNFQCKEDGIIAQAVDDSRVLLVSLEIGV...DEE'), id='sp|P15873|PCNA_YEAST', name='sp|P15873|PCNA_YEAST', description='sp|P15873|PCNA_YEAST Proliferating cell nuclear antigen OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=POL30 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSEFATSRVESGSQQTSIHSTPIVQKLETDESPIQTKSEYTNAELPAKPIAAYW...SEE'), id='sp|P23585|HXT2_YEAST', name='sp|P23585|HXT2_YEAST', description='sp|P23585|HXT2_YEAST High-affinity glucose transporter HXT2 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=HXT2 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MDDKVSEKESSPKQTEEDSEGKMAHVQPASYVNKKKYVFGKTLGAGTFGVVRQA...TEE'), id='sp|P27466|KCC1_YEAST', name='sp|P27466|KCC1_YEAST', description='sp|P27466|KCC1_YEAST Calcium/calmodulin-dependent protein kinase I OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CMK1 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MDFTKPETVLNLQNIRDELVRMEDSIIFKFIERSHFATCPSVYEANHPGLEIPN...LEE'), id='sp|P32178|CHMU_YEAST', name='sp|P32178|CHMU_YEAST', description='sp|P32178|CHMU_YEAST Chorismate mutase OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=ARO7 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MSGIIDASSALRKRKHLKRGITFTVMIVGQSGSGRSTFINTLCGQQVVDTSTTI...QEE'), id='sp|P32458|CDC11_YEAST', name='sp|P32458|CDC11_YEAST', description='sp|P32458|CDC11_YEAST Cell division control protein 11 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CDC11 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MAGKKGQKKSGLGNHGKNSDMDVEDRLQAVVLTDSYETRFMPLTAVKPRCLLPL...EEE'), id='sp|P32501|EI2BE_YEAST', name='sp|P32501|EI2BE_YEAST', description='sp|P32501|EI2BE_YEAST Translation initiation factor eIF2B subunit epsilon OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=GCD6 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MKVISLKKDSFNKGGAVITLLPEDKEDLFTVYQIVDKDDELIFKKKFTSKLDEA...GEE'), id='sp|P33309|DOM34_YEAST', name='sp|P33309|DOM34_YEAST', description='sp|P33309|DOM34_YEAST Protein DOM34 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=DOM34 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MPVVHVIDVESGNLQSLTNAIEHLGYEVQLVKSPKDFNISGTSRLILPGVGNYG...DEE'), id='sp|P33734|HIS5_YEAST', name='sp|P33734|HIS5_YEAST', description='sp|P33734|HIS5_YEAST Imidazole glycerol phosphate synthase hisHF OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=HIS7 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MSLTANDESPKPKKNALLKNLEIDDLIHSQFVRSDTNGHRTTRRLFNSDASISH...DEE'), id='sp|P34218|SAS3_YEAST', name='sp|P34218|SAS3_YEAST', description='sp|P34218|SAS3_YEAST Histone acetyltransferase SAS3 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=SAS3 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MTDITPVQNDVDVNGNNVNDDVSSNLKRPIDQGDPSNGLAEEENPANNQLHLKK...EEE'), id='sp|P35817|BDF1_YEAST', name='sp|P35817|BDF1_YEAST', description='sp|P35817|BDF1_YEAST Bromodomain-containing factor 1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=BDF1 PE=1 SV=3', dbxrefs=[]),
  SeqRecord(seq=Seq('MPFITSRPVAKNSSHSLSETDLNQSKGQPFQPSPTKKLGSMQQRRRSSTIRHAL...DEE'), id='sp|P38167|ECM21_YEAST', name='sp|P38167|ECM21_YEAST', description='sp|P38167|ECM21_YEAST Protein ECM21 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=ECM21 PE=1 SV=2', dbxrefs=[]),
  SeqRecord(seq=Seq('MSKKQEYIAPIKYQNSLPVPQLPPKLLVYPESPETNADSSQLINSLYIKTNVTN...QEE'), id='sp|P38351|PAF1_YEAST', name='sp|P38351|PAF1_YEAST', description='sp|P38351|PAF1_YEAST RNA polymerase II-associated protein 1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=PAF1 PE=1 SV=1', dbxrefs=[]),
  SeqRecord(seq=Seq('MVDESDKKQQTIDEQSQISPEKQTPNKKDKKKEEEEQLSEEDAKLKTDLELLVE...EEE'), id='sp|P38764|RPN1_YEAST', name='sp|P38764|RPN1_YEAST', description='sp|P38764|RPN1_YEAST 26S proteasome regulatory subunit RPN1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RPN1 PE=1 SV=3', dbxrefs=[]),
  SeqRecord(seq=Seq('MSEEFIAVSTLARNLEIAKGNEFHTILATLRSPVYINEQLLKSELSFLVTKILK...EEE'), id='sp|P38883|RIX1_YEAST', name='sp|P38883|RIX1_YEAST', description='sp|P38883|RIX1_YEAST Pre-rRNA-processing protein RIX1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RIX1 PE=1 SV=2', dbxrefs=[]),

In [20]:
#saving duplicate endings to dataframe and csv
ZZ_endings = {
    "id": [],
    "name": [],
    "description": [],
    "sequence": [],
    "duplicate_identity": []  
}

for amino_acid, seq_list in filtered_duplicates.items():
    for record in seq_list:
        ZZ_endings["id"].append(record.id)
        ZZ_endings["name"].append(record.name)
        ZZ_endings["description"].append(record.description)
        ZZ_endings["sequence"].append(str(record.seq))
        ZZ_endings["duplicate_identity"].append(amino_acid)  

for key, value in ZZ_endings.items():
    print(f"{key}: {len(value)}") 

df = pd.DataFrame(ZZ_endings)

df.to_csv('filtered_seqrecords_duplicates.csv', index=False)

print(df)

id: 560
name: 560
description: 560
sequence: 560
duplicate_identity: 560
                        id                   name  \
0    sp|P05740|RL17A_YEAST  sp|P05740|RL17A_YEAST
1     sp|P07702|LYS2_YEAST   sp|P07702|LYS2_YEAST
2     sp|P10964|RPA1_YEAST   sp|P10964|RPA1_YEAST
3     sp|P32318|THI4_YEAST   sp|P32318|THI4_YEAST
4    sp|P32472|FKBP2_YEAST  sp|P32472|FKBP2_YEAST
..                     ...                    ...
555   sp|Q12116|TMS1_YEAST   sp|Q12116|TMS1_YEAST
556  sp|P0C5M9|YF009_YEAST  sp|P0C5M9|YF009_YEAST
557   sp|P36127|YK12_YEAST   sp|P36127|YK12_YEAST
558  sp|Q3E7Z1|YN146_YEAST  sp|Q3E7Z1|YN146_YEAST
559  sp|Q3E7Z7|YD003_YEAST  sp|Q3E7Z7|YD003_YEAST

                                           description  \
0    sp|P05740|RL17A_YEAST Large ribosomal subunit ...
1    sp|P07702|LYS2_YEAST L-2-aminoadipate reductas...
2    sp|P10964|RPA1_YEAST DNA-directed RNA polymera...
3    sp|P32318|THI4_YEAST Thiamine thiazole synthas...
4    sp|P32472|FKBP2_YEAST Peptidyl-prolyl cis-tran...
..                                                 ...
555  sp|Q12116|TMS1_YEAST Membrane protein TMS1 OS=...
556  sp|P0C5M9|YF009_YEAST Uncharacterized protein ...
557  sp|P36127|YK12_YEAST Uncharacterized protein Y...
558  sp|Q3E7Z1|YN146_YEAST Uncharacterized protein ...
559  sp|Q3E7Z7|YD003_YEAST Uncharacterized protein ...

                                              sequence duplicate_identity
0    MARYGATSTNPAKSASARGSYLRVSFKNTRETAQAINGWELTKAQK...                 AA
1    MTNEKVWIEKLDNPTLSVLPHDFLRPQQEPYTKQATYSLQLPQLDV...                 AA
2    MDISKPVGSEITSVDFGILTAKEIRNLSAKQITNPTVLDNLGHPVS...                 AA
3    MSATSTATSTSASQLHLNSTPVTHCLSDIVKKEDWSDFKFAPIRES...                 AA
4    MMFNIYLFVTFFSTILAGSLSDLEIGIIKRIPVEDCLIKAMPGDKV...                 AA
..                                                 ...                ...
555  MGAVISLPVSMAGSFVASCFGGCCSNLVTKTASSLGSSSLGTRLLY...                 YY
556  MLNVSMITKWFTESTCKSLLTNTDTMLPNHRKLNQELRNWKNCPFW...                 YY
557  MAYSSLCLCLLFNPKGCSNLHPFVVDNEFPPYHLSLVLIKQQRMLD...                 YY
558  MISVCFVFPHSLALDFKSRCKKNRTKLCSAYYVSQVLRICKEMPYR...                 YY
559           MTCGIENSYKSAEKKKKYRSFRFFESRDYSELCIIVGTYY                 YY

[560 rows x 5 columns]

# Making master sequence file of +/-9 nucleotides surrounding stop codon for every gene in the yeast genome

In [24]:
#load fasta and gtf files
genome_seq = SeqIO.to_dict(SeqIO.parse("Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa", "fasta"))
in_file = "stop_codon_output.gtf"
#I have already filtered the gtf file from the original download by running this in command line:
#awk '$3 == "stop_codon"' Saccharomyces_cerevisiae.R64-1-1.110.gtf > stop_codon_output.gtf

In [25]:
#load GFFexaminer & examine gtf file
import pprint
from BCBio.GFF import GFFExaminer

examiner = GFFExaminer()
in_handle = open(in_file)
pprint.pprint(examiner.available_limits(in_handle))
in_handle.close()

{'gff_id': {('I',): 117,
            ('II',): 456,
            ('III',): 184,
            ('IV',): 836,
            ('IX',): 241,
            ('Mito',): 28,
            ('V',): 323,
            ('VI',): 139,
            ('VII',): 583,
            ('VIII',): 321,
            ('X',): 398,
            ('XI',): 348,
            ('XII',): 578,
            ('XIII',): 505,
            ('XIV',): 435,
            ('XV',): 597,
            ('XVI',): 511},
 'gff_source': {('sgd',): 6600},
 'gff_source_type': {('sgd', 'stop_codon'): 6600},
 'gff_type': {('stop_codon',): 6600}}

In [37]:
#This code is for filtering through the fasta file using the gtf file 
from BCBio import GFF
from Bio import SeqIO
import csv

# Read in the sequence file
in_seq_file = "Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa"
in_seq_handle = open(in_seq_file)
seq_dict = SeqIO.to_dict(SeqIO.parse(in_seq_handle, "fasta"))
in_seq_handle.close()

# Read in the expanded stop codon GTF file and extract ranges
ranges_data = []

# Parse the GFF/GTG file
in_handle = open(in_file)
for rec in GFF.parse(in_handle, base_dict=seq_dict):
    for feature in rec.features:
        if feature.type == "stop_codon":  #ensure we're only looking at stop codons 
            #(.gtf should be exclusively stop codons anyway)
            #this is the start and end of the stop codon
            original_start = feature.location.start
            original_end = feature.location.end
            
            # Expand range by 9 nucleotides on either side (total of 18)
            expanded_start = max(0, original_start - 9)  #avoid negatives
            expanded_end = original_end + 9 
            
            chromosome = rec.id
            gene_id = feature.qualifiers.get("gene_name", ["unknown"])[0]
            transcript_id = feature.qualifiers.get("transcript_id", ["unknown"])[0]
            strand = "+" if feature.location.strand == 1 else "-"  
            
            sequence = str(seq_dict[chromosome].seq[expanded_start:expanded_end])
            
            ranges_data.append([chromosome, gene_id, transcript_id, strand, expanded_start, expanded_end, sequence])

in_handle.close()

# Write to CSV file with sequences included
with open("stop_codon_ranges_with_sequences_yeast.csv", "w", newline='') as csvfile:
    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(["Chromosome", "Gene_name","Transcript_ID", "Strand", "Start", "End", "Sequence"])
    csv_writer.writerows(ranges_data)

print("Data saved to stop_codon_ranges_with_sequences_yeast.csv")

Data saved to stop_codon_ranges_with_sequences_yeast.csv

In [42]:
df_all = pd.read_csv('stop_codon_ranges_with_sequences_yeast.csv')
#cool, but negative strands will display reverse complemented sequences
#need to change that
df_all

,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence
0,I,unknown,YAL037W_mRNA,+,74811,74832,GGTCGCTTTTGAAGAGCCCTC
1,I,TPD3,YAL016W_mRNA,+,126774,126795,TTAAAAAATTGATACTAGTTC
2,I,EFB1,YAL003W_mRNA,+,143148,143169,CAAAAATTATAAAAGGCTTTT
3,I,FLC2,YAL053W_mRNA,+,48238,48259,CCATATTTGTAATCCAATATA
4,I,unknown,YAL031W-A_mRNA,+,84965,84986,ATTGGCGGATAATGTAGCACA
...,...,...,...,...,...,...,...
6595,XVI,HDA3,YPR179C_mRNA,-,893787,893808,TTTATTTAATTATACATTTCC
6596,XVI,unknown,YPR096C_mRNA,-,724832,724853,CAAAAGAATTCAAAGTACTAT
6597,XVI,ERG10,YPL028W_mRNA,+,499280,499301,GAAAAGATATGATTACGTTCT
6598,XVI,NIP100,YPL174C_mRNA,-,220157,220178,ATCACTCAGTCATTTGTAATA
6599,XVI,NTO1,YPR031W_mRNA,+,633749,633770,AACAGCGGATAAAATAAAGGT

In [77]:
def reverse_complement(seq):
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    return ''.join(complement[base] for base in reversed(seq))

#reverse complement sequence based on strand
def replace_with_reverse_complement(row):
    if row['Strand']=="-":
        row['Sequence'] = reverse_complement(row['Sequence'])
    return row

df_all_new = df_all.apply(replace_with_reverse_complement, axis=1)

#drop _mRNA, add new columns for stop codon, +4 nucleotide and 3UTR codon
df_all_new['Transcript_ID'] = df_all_new['Transcript_ID'].str.replace('_mRNA', '')
df_all_new['Stop Codon'] = df_all_new['Sequence'].str[9:12]
df_all_new['+4 nucleotide'] = df_all_new['Sequence'].str[12:13]
df_all_new['3UTR codon'] = df_all_new['Sequence'].str[12:15]

#save the resulting DataFrame (this now contains all strands in the 5 to 3 direction)
df_all_new.to_csv('whole_genome_stop_ranges_060326.csv', index=False)

df_all_new

,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon
0,I,unknown,YAL037W,+,74811,74832,GGTCGCTTTTGAAGAGCCCTC,TGA,A,AGA
1,I,TPD3,YAL016W,+,126774,126795,TTAAAAAATTGATACTAGTTC,TGA,T,TAC
2,I,EFB1,YAL003W,+,143148,143169,CAAAAATTATAAAAGGCTTTT,TAA,A,AAG
3,I,FLC2,YAL053W,+,48238,48259,CCATATTTGTAATCCAATATA,TAA,T,TCC
4,I,unknown,YAL031W-A,+,84965,84986,ATTGGCGGATAATGTAGCACA,TAA,T,TGT
...,...,...,...,...,...,...,...,...,...,...
6595,XVI,HDA3,YPR179C,-,893787,893808,GGAAATGTATAATTAAATAAA,TAA,T,TTA
6596,XVI,unknown,YPR096C,-,724832,724853,ATAGTACTTTGAATTCTTTTG,TGA,A,ATT
6597,XVI,ERG10,YPL028W,+,499280,499301,GAAAAGATATGATTACGTTCT,TGA,T,TTA
6598,XVI,NIP100,YPL174C,-,220157,220178,TATTACAAATGACTGAGTGAT,TGA,C,CTG
6599,XVI,NTO1,YPR031W,+,633749,633770,AACAGCGGATAAAATAAAGGT,TAA,A,AAT

In [53]:
#loading gene names downloaded from https://www.alliancegenome.org/bluegenes/alliancemine/results/ALL_Yeast_Genes
#this is to match common gene name to systematic gene name since the proteome 
mapping_df = pd.read_csv('gene_names.csv')
mapping_df

,Gene > Primary DBID,Gene > Systematic Name,Gene > Organism . Short Name,Gene > Standard Name,Gene > Name
0,SGD:L000003336,YCLX01W,S. cerevisiae,NaN,NaN
1,SGD:S000000001,YAL001C,S. cerevisiae,TFC3,Transcription Factor class C
2,SGD:S000000002,YAL002W,S. cerevisiae,VPS8,Vacuolar Protein Sorting
3,SGD:S000000003,YAL003W,S. cerevisiae,EFB1,Elongation Factor Beta
4,SGD:S000000004,YAL005C,S. cerevisiae,SSA1,Stress-Seventy subfamily A
...,...,...,...,...,...
7168,SGD:S000350095,YFR035W-A,S. cerevisiae,NaN,NaN
7169,SGD:S000350096,YGR016C-A,S. cerevisiae,NaN,NaN
7170,SGD:S000350097,YMR106W-A,S. cerevisiae,NaN,NaN
7171,SGD:S000350098,YNL040C-A,S. cerevisiae,NaN,NaN
7172,SGD:S000350099,YNL155C-A,S. cerevisiae,NaN,NaN

In [51]:
gene_mapping = dict(zip(mapping_df['Gene > Systematic Name'], mapping_df['Gene > Standard Name']))
gene_mapping

{'YCLX01W': nan,
 'YAL001C': 'TFC3',
 'YAL002W': 'VPS8',
 'YAL003W': 'EFB1',
 'YAL005C': 'SSA1',
 'YAL007C': 'ERP2',
 'YAL008W': 'FUN14',
 'YAL009W': 'SPO7',
 'YAL010C': 'MDM10',
 'YAL011W': 'SWC3',
 'YAL012W': 'CYS3',
 'YAL013W': 'DEP1',
 'YAL014C': 'SYN8',
 'YAL015C': 'NTG1',
 'YAL016W': 'TPD3',
 'YAL017W': 'PSK1',
 'YAL018C': 'LDS1',
 'YAL019W': 'FUN30',
 'YAL020C': 'ATS1',
 'YAL021C': 'CCR4',
 'YAL022C': 'FUN26',
 'YAL023C': 'PMT2',
 'YAL024C': 'LTE1',
 'YAL025C': 'MAK16',
 'YAL026C': 'DRS2',
 'YAL027W': 'SAW1',
 'YAL028W': 'FRT2',
 'YAL029C': 'MYO4',
 'YAL030W': 'SNC1',
 'YAL031C': 'GIP4',
 'YAL032C': 'PRP45',
 'YAL033W': 'POP5',
 'YAL034W-A': 'MTW1',
 'YAL035W': 'FUN12',
 'YAL036C': 'RBG1',
 'YAL037W': nan,
 'YAL038W': 'CDC19',
 'YAL039C': 'CYC3',
 'YAL040C': 'CLN3',
 'YAL041W': 'CDC24',
 'YAL042W': 'ERV46',
 'YAL043C': 'PTA1',
 'YAL044C': 'GCV3',
 'YAL045C': nan,
 'YAL046C': 'BOL3',
 'YAL047C': 'SPC72',
 'YAL048C': 'GEM1',
 'YAL049C': 'AIM2',
 'YAL051W': 'OAF1',
 'YAL053W': 'FLC2',
 'YAL054C': 'ACS1',
 'YAL055W': 'PEX22',
 'YAL056W': 'GPB2',
 'YAL058W': 'CNE1',
 'YAL059W': 'ECM1',
 'YAL060W': 'BDH1',
 'YAL061W': 'BDH2',
 'YAL062W': 'GDH3',
 'YAL063C': 'FLO9',
 'YAL064W': nan,
 'YAL066W': nan,
 'YAL067C': 'SEO1',
 'YAR002W': 'NUP60',
 'YAR003W': 'SWD1',
 'YAR007C': 'RFA1',
 'YAR008W': 'SEN34',
 'YAR014C': 'BUD14',
 'YAR015W': 'ADE1',
 'YAR018C': 'KIN3',
 'YAR019C': 'CDC15',
 'YAR020C': 'PAU7',
 'YAR023C': 'DFP1',
 'YAR027W': 'UIP3',
 'YAR028W': 'KTD1',
 'YAR029W': 'DFP2',
 'YAR031W': 'PRM9',
 'YAR033W': 'MST28',
 'YAR035W': 'YAT1',
 'YAR042W': 'SWH1',
 'YAR044W': nan,
 'YAR047C': nan,
 'YAR050W': 'FLO1',
 'YAR053W': nan,
 'YAR060C': nan,
 'YAR061W': nan,
 'YAR062W': nan,
 'YAR064W': nan,
 'YAR068W': nan,
 'YAR069C': nan,
 'YAR070C': nan,
 'YAR071W': 'PHO11',
 'YAR073W': 'IMD1',
 'YBL001C': 'ECM15',
 'YBL002W': 'HTB2',
 'YBL003C': 'HTA2',
 'YBL004W': 'UTP20',
 'YBL005W': 'PDR3',
 'YBL006C': 'LDB7',
 'YBL007C': 'SLA1',
 'YBL008W': 'HIR1',
 'YBL009W': 'ALK2',
 'YBL010C': 'LAA2',
 'YBL011W': 'SCT1',
 'YBL012C': nan,
 'YBL013W': 'FMT1',
 'YBL014C': 'RRN6',
 'YBL015W': 'ACH1',
 'YBL016W': 'FUS3',
 'YBL017C': 'PEP1',
 'YBL018C': 'POP8',
 'YBL019W': 'APN2',
 'YBL020W': 'RFT1',
 'YBL021C': 'HAP3',
 'YBL022C': 'PIM1',
 'YBL023C': 'MCM2',
 'YBL024W': 'NCL1',
 'YBL025W': 'RRN10',
 'YBL026W': 'LSM2',
 'YBL027W': 'RPL19B',
 'YBL028C': nan,
 'YBL029W': nan,
 'YBL030C': 'PET9',
 'YBL031W': 'SHE1',
 'YBL032W': 'HEK2',
 'YBL033C': 'RIB1',
 'YBL034C': 'STU1',
 'YBL035C': 'POL12',
 'YBL036C': nan,
 'YBL037W': 'APL3',
 'YBL038W': 'MRPL16',
 'YBL039C': 'URA7',
 'YBL040C': 'ERD2',
 'YBL041W': 'PRE7',
 'YBL042C': 'FUI1',
 'YBL043W': 'ECM13',
 'YBL044W': nan,
 'YBL045C': 'COR1',
 'YBL046W': 'PSY4',
 'YBL047C': 'EDE1',
 'YBL048W': 'RRT1',
 'YBL049W': 'MOH1',
 'YBL050W': 'SEC17',
 'YBL051C': 'PIN4',
 'YBL052C': 'SAS3',
 'YBL053W': nan,
 'YBL054W': 'TOD6',
 'YBL055C': nan,
 'YBL056W': 'PTC3',
 'YBL057C': 'PTH2',
 'YBL058W': 'SHP1',
 'YBL059W': 'IAI11',
 'YBL060W': 'YEL1',
 'YBL061C': 'SKT5',
 'YBL062W': nan,
 'YBL063W': 'KIP1',
 'YBL064C': 'PRX1',
 'YBL065W': nan,
 'YBL066C': 'SEF1',
 'YBL067C': 'UBP13',
 'YBL068W': 'PRS4',
 'YBL069W': 'AST1',
 'YBL070C': nan,
 'YBL071C': nan,
 'YBL072C': 'RPS8A',
 'YBL073W': nan,
 'YBL074C': 'AAR2',
 'YBL075C': 'SSA3',
 'YBL076C': 'ILS1',
 'YBL077W': nan,
 'YBL078C': 'ATG8',
 'YBL079W': 'NUP170',
 'YBL080C': 'PET112',
 'YBL081W': nan,
 'YBL082C': 'ALG3',
 'YBL083C': nan,
 'YBL084C': 'CDC27',
 'YBL085W': 'BOI1',
 'YBL086C': nan,
 'YBL087C': 'RPL23A',
 'YBL088C': 'TEL1',
 'YBL089W': 'AVT5',
 'YBL090W': 'MRP21',
 'YBL091C': 'MAP2',
 'YBL092W': 'RPL32',
 'YBL093C': 'ROX3',
 'YBL094C': nan,
 'YBL095W': 'MRX3',
 'YBL096C': nan,
 'YBL097W': 'BRN1',
 'YBL098W': 'BNA4',
 'YBL099W': 'ATP1',
 'YBL100C': nan,
 'YBL101C': 'ECM21',
 'YBL102W': 'SFT2',
 'YBL103C': 'RTG3',
 'YBL104C': 'SEA4',
 'YBL105C': 'PKC1',
 'YBL106C': 'SRO77',
 'YBL107C': 'MIX23',
 'YBL108W': nan,
 'YBR001C': 'NTH2',
 'YBR002C': 'RER2',
 'YBR003W': 'COQ1',
 'YBR004C': 'GPI18',
 'YBR005W': 'RCR1',
 'YBR006W': 'UGA2',
 'YBR007C': 'DSF2',
 'YBR008C': 'FLR1',
 'YBR009C': 'HHF1',
 'YBR010W': 'HHT1',
 'YBR011C': 'IPP1',
 'YBR012C': nan,
 'YBR013C': nan,
 'YBR014C': 'GRX7',
 'YBR015C': 'MNN2',
 'YBR016W': 'CPP1',
 'YBR017C': 'KAP104',
 'YBR018C': 'GAL7',
 'YBR019C': 'GAL10',
 'YBR020W': 'GAL1',
 'YBR021W': 'FUR4',
 'YBR022W': 'POA1',
 'YBR023C': 'CHS3',
 'YBR024W': 'SCO2',
 'YBR025C': 'OLA1',
 'YBR026C': 'ETR1',
 'YBR027C': nan,
 'YBR028C': 'YPK3',
 'YBR029C': 'CDS1',
 'YBR030W': 'RKM3',
 'YBR031W': 'RPL4A',
 'YBR032W': nan,
 'YBR033W': 'EDS1',
 'YBR034C': 'HMT1',
 'YBR035C': 'PDX3',
 'YBR036C': 'CSG2',
 'YBR037C': 'SCO1',
 'YBR038W': 'CHS2',
 'YBR039W': 'ATP3',
 'YBR040W': 'FIG1',
 'YBR041W': 'FAT1',
 'YBR042C': 'CST26',
 'YBR043C': 'QDR3',
 'YBR044C': 'TCM62',
 'YBR045C': 'GIP1',
 'YBR046C': 'ZTA1',
 'YBR047W': 'FMP23',
 'YBR048W': 'RPS11B',
 'YBR049C': 'REB1',
 'YBR050C': 'REG2',
 'YBR051W': nan,
 'YBR052C': 'RFS1',
 'YBR053C': nan,
 'YBR054W': 'YRO2',
 'YBR055C': 'PRP6',
 'YBR056W': 'MRX18',
 'YBR057C': 'MUM2',
 'YBR058C': 'UBP14',
 'YBR059C': 'AKL1',
 'YBR060C': 'ORC2',
 'YBR061C': 'TRM7',
 'YBR062C': nan,
 'YBR063C': 'CNM1',
 'YBR064W': nan,
 'YBR065C': 'ECM2',
 'YBR066C': 'NRG2',
 'YBR067C': 'TIP1',
 'YBR068C': 'BAP2',
 'YBR069C': 'TAT1',
 'YBR070C': 'ALG14',
 'YBR071W': nan,
 'YBR072W': 'HSP26',
 'YBR073W': 'RDH54',
 'YBR074W': 'PFF1',
 'YBR075W': nan,
 'YBR076W': 'ECM8',
 'YBR077C': 'SLM4',
 'YBR078W': 'ECM33',
 'YBR079C': 'RPG1',
 'YBR080C': 'SEC18',
 'YBR081C': 'SPT7',
 'YBR082C': 'UBC4',
 'YBR083W': 'TEC1',
 'YBR084W': 'MIS1',
 'YBR085W': 'AAC3',
 'YBR086C': 'IST2',
 'YBR087W': 'RFC5',
 'YBR088C': 'POL30',
 'YBR089W': nan,
 'YBR090C': nan,
 'YBR091C': 'TIM12',
 'YBR092C': 'PHO3',
 'YBR093C': 'PHO5',
 'YBR094W': 'PBY1',
 'YBR095C': 'RXT2',
 'YBR096W': nan,
 'YBR097W': 'VPS15',
 'YBR098W': 'MMS4',
 'YBR099C': nan,
 'YBR100W': nan,
 'YBR101C': 'FES1',
 'YBR102C': 'EXO84',
 'YBR103W': 'SIF2',
 'YBR104W': 'YMC2',
 'YBR105C': 'VID24',
 'YBR106W': 'SND3',
 'YBR107C': 'IML3',
 'YBR108W': 'AIM3',
 'YBR109C': 'CMD1',
 'YBR110W': 'ALG1',
 'YBR111C': 'YSA1',
 'YBR112C': 'CYC8',
 'YBR113W': nan,
 'YBR114W': 'RAD16',
 'YBR115C': 'LYS2',
 'YBR116C': nan,
 'YBR117C': 'TKL2',
 'YBR118W': 'TEF2',
 'YBR119W': 'MUD1',
 'YBR120C': 'CBP6',
 'YBR121C': 'GRS1',
 'YBR122C': 'MRPL36',
 'YBR123C': 'TFC1',
 'YBR124W': nan,
 'YBR125C': 'PTC4',
 'YBR126C': 'TPS1',
 'YBR127C': 'VMA2',
 'YBR128C': 'ATG14',
 'YBR129C': 'OPY1',
 'YBR130C': 'SHE3',
 'YBR131W': 'CCZ1',
 'YBR132C': 'AGP2',
 'YBR133C': 'HSL7',
 'YBR134W': nan,
 'YBR135W': 'CKS1',
 'YBR136W': 'MEC1',
 'YBR137W': nan,
 'YBR138C': nan,
 'YBR139W': 'ATG42',
 'YBR140C': 'IRA1',
 'YBR141C': 'BMT2',
 'YBR142W': 'MAK5',
 'YBR143C': 'SUP45',
 'YBR144C': nan,
 'YBR145W': 'ADH5',
 'YBR146W': 'MRPS9',
 'YBR147W': 'RTC2',
 'YBR148W': 'YSW1',
 'YBR149W': 'ARA1',
 'YBR150C': 'TBS1',
 'YBR151W': 'APD1',
 'YBR152W': 'SPP381',
 'YBR153W': 'RIB7',
 'YBR154C': 'RPB5',
 'YBR155W': 'CNS1',
 'YBR156C': 'SLI15',
 'YBR157C': 'ICS2',
 'YBR158W': 'AMN1',
 'YBR159W': 'IFA38',
 'YBR160W': 'CDC28',
 'YBR161W': 'CSH1',
 'YBR162C': 'TOS1',
 'YBR163W': 'EXO5',
 'YBR164C': 'ARL1',
 'YBR165W': 'UBS1',
 'YBR166C': 'TYR1',
 'YBR167C': 'POP7',
 'YBR168W': 'PEX32',
 'YBR169C': 'SSE2',
 'YBR170C': 'NPL4',
 'YBR171W': 'SEC66',
 'YBR172C': 'SMY2',
 'YBR173C': 'UMP1',
 'YBR174C': nan,
 'YBR175W': 'SWD3',
 'YBR176W': 'ECM31',
 'YBR177C': 'EHT1',
 'YBR178W': nan,
 'YBR179C': 'FZO1',
 'YBR180W': 'DTR1',
 'YBR181C': 'RPS6B',
 'YBR182C': 'SMP1',
 'YBR183W': 'YPC1',
 'YBR184W': nan,
 'YBR185C': 'MBA1',
 'YBR186W': 'PCH2',
 'YBR187W': 'GDT1',
 'YBR188C': 'NTC20',
 'YBR189W': 'RPS9B',
 'YBR190W': nan,
 'YBR191W': 'RPL21A',
 'YBR192W': 'RIM2',
 'YBR193C': 'MED8',
 'YBR194W': 'AIM4',
 'YBR195C': 'MSI1',
 'YBR196C': 'PGI1',
 'YBR197C': nan,
 'YBR198C': 'TAF5',
 'YBR199W': 'KTR4',
 'YBR200W': 'BEM1',
 'YBR201W': 'DER1',
 'YBR202W': 'MCM7',
 'YBR203W': 'COS111',
 'YBR204C': 'LDH1',
 'YBR205W': 'KTR3',
 'YBR206W': nan,
 'YBR207W': 'FTH1',
 'YBR208C': 'DUR12',
 'YBR209W': nan,
 'YBR210W': 'ERV15',
 'YBR211C': 'AME1',
 'YBR212W': 'NGR1',
 'YBR213W': 'MET8',
 'YBR214W': 'SDS24',
 'YBR215W': 'HPC2',
 'YBR216C': 'YBP1',
 'YBR217W': 'ATG12',
 'YBR218C': 'PYC2',
 'YBR219C': nan,
 'YBR220C': nan,
 'YBR221C': 'PDB1',
 'YBR222C': 'PCS60',
 'YBR223C': 'TDP1',
 'YBR224W': nan,
 'YBR225W': nan,
 'YBR226C': nan,
 'YBR227C': 'MCX1',
 'YBR228W': 'SLX1',
 'YBR229C': 'ROT2',
 'YBR230C': 'OM14',
 'YBR231C': 'SWC5',
 'YBR232C': nan,
 'YBR233W': 'PBP2',
 'YBR234C': 'ARC40',
 'YBR235W': 'VHC1',
 'YBR236C': 'ABD1',
 'YBR237W': 'PRP5',
 'YBR238C': nan,
 'YBR239C': 'ERT1',
 'YBR240C': 'THI2',
 'YBR241C': 'VVS1',
 'YBR242W': nan,
 'YBR243C': 'ALG7',
 'YBR244W': 'GPX2',
 'YBR245C': 'ISW1',
 'YBR246W': 'RRT2',
 'YBR247C': 'ENP1',
 'YBR248C': 'HIS7',
 'YBR249C': 'ARO4',
 'YBR250W': 'SPO23',
 'YBR251W': 'MRPS5',
 'YBR252W': 'DUT1',
 'YBR253W': 'SRB6',
 'YBR254C': 'TRS20',
 'YBR255W': 'MTC4',
 'YBR256C': 'RIB5',
 'YBR257W': 'POP4',
 'YBR258C': 'SHG1',
 'YBR259W': nan,
 'YBR260C': 'RGD1',
 'YBR261C': 'TAE1',
 'YBR262C': 'MIC12',
 'YBR263W': 'SHM1',
 'YBR264C': 'YPT10',
 'YBR265W': 'TSC10',
 'YBR266C': 'SLM6',
 'YBR267W': 'REI1',
 'YBR268W': 'MRPL37',
 'YBR269C': 'SDH8',
 'YBR270C': 'BIT2',
 'YBR271W': 'EFM2',
 'YBR272C': 'HSM3',
 'YBR273C': 'UBX7',
 'YBR274W': 'CHK1',
 'YBR275C': 'RIF1',
 'YBR276C': 'PPS1',
 'YBR277C': nan,
 'YBR278W': 'DPB3',
 'YBR279W': 'PAF1',
 'YBR280C': 'SAF1',
 'YBR281C': 'DUG2',
 'YBR282W': 'MRPL27',
 'YBR283C': 'SSH1',
 'YBR284W': nan,
 'YBR285W': 'HAB1',
 'YBR286W': 'APE3',
 'YBR287W': nan,
 'YBR288C': 'APM3',
 'YBR289W': 'SNF5',
 'YBR290W': 'BSD2',
 'YBR291C': 'CTP1',
 'YBR292C': nan,
 'YBR293W': 'VBA2',
 'YBR294W': 'SUL1',
 'YBR295W': 'PCA1',
 'YBR296C': 'PHO89',
 'YBR297W': 'MAL33',
 'YBR298C': 'MAL31',
 'YBR299W': 'MAL32',
 'YBR300C': nan,
 'YBR301W': 'PAU24',
 'YBR302C': 'COS2',
 'YCL001W': 'RER1',
 'YCL002C': nan,
 'YCL003W': nan,
 'YCL004W': 'PGS1',
 'YCL005W': 'LDB16',
 'YCL006C': nan,
 'YCL007C': nan,
 'YCL008C': 'STP22',
 'YCL009C': 'ILV6',
 'YCL010C': 'SGF29',
 'YCL011C': 'GBP2',
 'YCL012W': nan,
 'YCL013W': nan,
 'YCL014W': 'BUD3',
 'YCL016C': 'DCC1',
 'YCL017C': 'NFS1',
 'YCL018W': 'LEU2',
 'YCL021W': nan,
 'YCL022C': nan,
 'YCL023C': nan,
 'YCL024W': 'KCC4',
 'YCL025C': 'AGP1',
 'YCL026C': nan,
 'YCL027W': 'FUS1',
 'YCL028W': 'RNQ1',
 'YCL029C': 'BIK1',
 'YCL030C': 'HIS4',
 'YCL031C': 'RRP7',
 'YCL032W': 'STE50',
 'YCL033C': 'MXR2',
 'YCL034W': 'LSB5',
 'YCL035C': 'GRX1',
 'YCL036W': 'GFD2',
 'YCL037C': 'SRO9',
 'YCL038C': 'ATG22',
 'YCL039W': 'GID7',
 'YCL040W': 'GLK1',
 'YCL041C': nan,
 'YCL042W': nan,
 'YCL043C': 'PDI1',
 'YCL044C': 'MGR1',
 'YCL045C': 'EMC1',
 'YCL046W': nan,
 'YCL047C': 'POF1',
 'YCL048W': 'SPS22',
 'YCL049C': nan,
 'YCL050C': 'APA1',
 'YCL051W': 'LRE1',
 'YCL052C': 'PBN1',
 'YCL053C': nan,
 'YCL054W': 'SPB1',
 'YCL055W': 'KAR4',
 'YCL056C': 'PEX34',
 'YCL057W': 'PRD1',
 'YCL058C': 'FYV5',
 'YCL059C': 'KRR1',
 'YCL060C': nan,
 'YCL061C': 'MRC1',
 'YCL062W': nan,
 'YCL063W': 'VAC17',
 'YCL064C': 'CHA1',
 'YCL065W': nan,
 'YCL066W': 'HMLALPHA1',
 'YCL067C': 'HMLALPHA2',
 'YCL068C': nan,
 'YCL069W': 'VBA3',
 'YCL073C': 'GEX1',
 'YCL074W': nan,
 'YCL075W': nan,
 'YCL076W': nan,
 'YCLX03C': nan,
 'YCLX04W': nan,
 'YCLX05C': nan,
 'YCLX06C': nan,
 'YCLX07W': nan,
 'YCL026C-A': 'FRM2',
 'YCLX09W': nan,
 'YCLX10C': nan,
 'YCLX11W': nan,
 'YCLX12W': nan,
 'YCR001W': nan,
 'YCR002C': 'CDC10',
 'YCR003W': 'MRPL32',
 'YCR004C': 'YCP4',
 'YCR005C': 'CIT2',
 'YCR006C': nan,
 'YCR007C': 'DFP3',
 'YCR008W': 'SAT4',
 'YCR009C': 'RVS161',
 'YCR010C': 'ADY2',
 'YCR011C': 'ADP1',
 'YCR012W': 'PGK1',
 'YCR013C': nan,
 'YCR014C': 'POL4',
 'YCR015C': 'CTO1',
 'YCR016W': 'RBP95',
 'YCR017C': 'CWH43',
 'YCR018C': 'SRD1',
 'YCR019W': 'MAK32',
 'YCR020C': 'PET18',
 'YCR020C-A': 'MAK31',
 'YCR021C': 'HSP30',
 'YCR022C': nan,
 'YCR023C': nan,
 'YCR024C': 'SLM5',
 'YCR024C-A': 'PMP1',
 'YCR025C': nan,
 'YCR026C': 'NPP1',
 'YCR027C': 'RHB1',
 'YCR028C': 'FEN2',
 'YCR029C': nan,
 'YCR029C-A': nan,
 'YCR030C': 'SYP1',
 'YCR031C': 'RPS14A',
 'YCR032W': 'BPH1',
 'YCR033W': 'SNT1',
 'YCR034W': 'ELO2',
 'YCR035C': 'RRP43',
 'YCR036W': 'RBK1',
 'YCR037C': 'PHO87',
 'YCR038C': 'BUD5',
 'YCR039C': 'MATALPHA2',
 'YCR040W': 'MATALPHA1',
 'YCR041W': nan,
 'YCR042C': 'TAF2',
 'YCR043C': nan,
 'YCR044C': 'PER1',
 'YCR045C': 'RRT12',
 'YCR046C': 'IMG1',
 'YCR047C': 'BUD23',
 'YCR048W': 'ARE1',
 'YCR049C': nan,
 'YCR050C': nan,
 'YCR051W': nan,
 'YCR052W': 'RSC6',
 'YCR053W': 'THR4',
 'YCR054C': 'CTR86',
 'YCR055C': nan,
 'YCR056W': nan,
 'YCR057C': 'PWP2',
 'YCR058C': nan,
 'YCR059C': 'YIH1',
 'YCR060W': 'TAH1',
 'YCR061W': 'TVS1',
 'YCR062W': nan,
 'YCR063W': 'BUD31',
 'YCR064C': nan,
 'YCR065W': 'HCM1',
 'YCR066W': 'RAD18',
 'YCR067C': 'SED4',
 'YCR068W': 'ATG15',
 'YCR069W': 'CPR4',
 'YCR070W': nan,
 'YCR071C': 'IMG2',
 'YCR072C': 'RSA4',
 'YCR073C': 'SSK22',
 'YCR075C': 'ERS1',
 'YCR076C': 'FUB1',
 'YCR077C': 'PAT1',
 'YCR080W': nan,
 'YCR081W': 'SRB8',
 'YCR082W': 'AHC2',
 'YCR083W': 'TRX3',
 'YCR084C': 'TUP1',
 'YCR085W': nan,
 'YCR086W': 'CSM1',
 'YCR087W': nan,
 'YCR088W': 'ABP1',
 'YCR089W': 'FIG2',
 'YCR090C': nan,
 'YCR091W': 'KIN82',
 'YCR092C': 'MSH3',
 'YCR093W': 'CDC39',
 'YCR094W': 'CDC50',
 'YCR095C': 'OCA4',
 'YCR096C': 'HMRA2',
 'YCR097WA': nan,
 'YCR097W': 'HMRA1',
 'YCR098C': 'GIT1',
 'YCR099C': nan,
 'YCR100C': 'EMA35',
 'YCR101C': nan,
 'YCR102C': nan,
 'YCR103C': nan,
 'YCR104W': 'PAU3',
 'YCR105W': 'ADH7',
 'YCR106W': 'RDS1',
 'YCR107W': 'AAD3',
 'YCRX03C': nan,
 'YCRX05W': nan,
 'YCRX07W': nan,
 'YCRX10W': nan,
 'YCRX12W': nan,
 'YCR073W-A': 'SOL2',
 'YCRX14W': nan,
 'YCRX15W': nan,
 'YCRX16C': nan,
 'YCRX18C': nan,
 'YCRX20C': nan,
 'YCRX21C': nan,
 'YEL001C': 'IRC22',
 'YEL002C': 'WBP1',
 'YEL003W': 'GIM4',
 'YEL004W': 'YEA4',
 'YEL005C': 'VAB2',
 'YEL006W': 'YEA6',
 'YEL007W': 'MIT1',
 'YEL008W': nan,
 'YEL009C': 'GCN4',
 'YEL010W': nan,
 'YEL011W': 'GLC3',
 'YEL012W': 'UBC8',
 'YEL013W': 'VAC8',
 'YEL014C': nan,
 'YEL015W': 'EDC3',
 'YEL016C': 'NPP2',
 'YEL017W': 'GTT3',
 'YEL018W': 'EAF5',
 'YEL019C': 'MMS21',
 'YEL020C': 'PXP1',
 'YEL021W': 'URA3',
 'YEL022W': 'GEA2',
 'YEL023C': nan,
 'YEL024W': 'RIP1',
 'YEL025C': nan,
 'YEL026W': 'SNU13',
 'YEL027W': 'VMA3',
 'YEL028W': nan,
 'YEL029C': 'BUD16',
 'YEL030W': 'ECM10',
 'YEL031W': 'SPF1',
 'YEL032W': 'MCM3',
 'YEL033W': 'MTC7',
 'YEL034W': 'HYP2',
 'YEL035C': 'UTR5',
 'YEL036C': 'ANP1',
 'YEL037C': 'RAD23',
 'YEL038W': 'UTR4',
 'YEL039C': 'CYC7',
 'YEL040W': 'UTR2',
 'YEL041W': 'YEF1',
 'YEL042W': 'GDA1',
 'YEL043W': 'GTA1',
 'YEL044W': 'IES6',
 'YEL045C': nan,
 'YEL046C': 'GLY1',
 'YEL047C': 'FRD1',
 'YEL048C': 'TCA17',
 'YEL049W': 'PAU2',
 'YEL050C': 'RML2',
 'YEL051W': 'VMA8',
 'YEL052W': 'AFG1',
 'YEL053C': 'MAK10',
 'YEL054C': 'RPL12A',
 'YEL055C': 'POL5',
 'YEL056W': 'HAT2',
 'YEL057C': 'SDD1',
 'YEL058W': 'PCM1',
 'YEL059W': 'HHY1',
 'YEL060C': 'PRB1',
 'YEL061C': 'CIN8',
 'YEL062W': 'NPR2',
 'YEL063C': 'CAN1',
 'YEL064C': 'AVT2',
 'YEL065W': 'SIT1',
 'YEL066W': 'HPA3',
 'YEL067C': nan,
 'YEL068C': nan,
 'YEL069C': 'HXT13',
 'YEL070W': 'DSF1',
 'YEL071W': 'DLD3',
 'YEL072W': 'RMD6',
 'YEL073C': nan,
 'YEL074W': nan,
 'YEL075C': nan,
 'YEL076C': nan,
 'YER001W': 'MNN1',
 'YER002W': 'NOP16',
 'YER003C': 'PMI40',
 'YER004W': 'FMP52',
 'YER005W': 'YND1',
 'YER006W': 'NUG1',
 'YER007W': 'PAC2',
 'YER008C': 'SEC3',
 'YER009W': 'NTF2',
 'YER010C': nan,
 'YER011W': 'TIR1',
 'YER012W': 'PRE1',
 'YER013W': 'PRP22',
 'YER014W': 'HEM14',
 'YER015W': 'FAA2',
 'YER016W': 'BIM1',
 'YER017C': 'AFG3',
 'YER018C': 'SPC25',
 'YER019W': 'ISC1',
 'YER020W': 'GPA2',
 'YER021W': 'RPN3',
 'YER022W': 'SRB4',
 'YER023W': 'PRO3',
 'YER024W': 'YAT2',
 'YER025W': 'GCD11',
 'YER026C': 'CHO1',
 'YER027C': 'GAL83',
 'YER028C': 'MIG3',
 'YER029C': 'SMB1',
 'YER030W': 'CHZ1',
 'YER031C': 'YPT31',
 'YER032W': 'FIR1',
 'YER033C': 'ZRG8',
 'YER034W': nan,
 'YER035W': 'EDC2',
 'YER036C': 'ARB1',
 'YER037W': 'PHM8',
 'YER038C': 'KRE29',
 'YER039C': 'HVG1',
 'YER040W': 'GLN3',
 'YER041W': 'YEN1',
 'YER042W': 'MXR1',
 'YER043C': 'SAH1',
 'YER044C': 'ERG28',
 'YER045C': 'ACA1',
 'YER046W': 'SPO73',
 'YER047C': 'SAP1',
 'YER048C': 'CAJ1',
 'YER049W': 'TPA1',
 'YER050C': 'RSM18',
 'YER051W': 'JHD1',
 'YER052C': 'HOM3',
 'YER053C': 'PIC2',
 'YER054C': 'GIP2',
 'YER055C': 'HIS1',
 'YER056C': 'FCY2',
 'YER057C': 'HMF1',
 'YER058W': 'PET117',
 'YER059W': 'PCL6',
 'YER060W': 'FCY21',
 'YER061C': 'CEM1',
 'YER062C': 'GPP2',
 'YER063W': 'THO1',
 'YER064C': 'VHR2',
 'YER065C': 'ICL1',
 'YER066W': 'RRT13',
 'YER067W': 'RGI1',
 'YER068W': 'MOT2',
 'YER069W': 'ARG56',
 'YER070W': 'RNR1',
 'YER071C': 'TDA2',
 'YER072W': 'VTC1',
 'YER073W': 'ALD5',
 'YER074W': 'RPS24A',
 'YER075C': 'PTP3',
 'YER076C': nan,
 'YER077C': 'MRX1',
 'YER078C': 'ICP55',
 'YER079W': nan,
 'YER080W': 'AIM9',
 'YER081W': 'SER3',
 'YER082C': 'UTP7',
 'YER083C': 'GET2',
 'YER084W': nan,
 'YER085C': nan,
 'YER086W': 'ILV1',
 'YER087W': 'AIM10',
 'YER088C': 'DOT6',
 'YER089C': 'PTC2',
 'YER090W': 'TRP2',
 'YER091C': 'MET6',
 'YER092W': 'IES5',
 'YER093C': 'TSC11',
 'YER094C': 'PUP3',
 'YER095W': 'RAD51',
 'YER096W': 'SHC1',
 'YER097W': nan,
 'YER098W': 'UBP9',
 'YER099C': 'PRS2',
 'YER100W': 'UBC6',
 'YER101C': 'AST2',
 'YER102W': 'RPS8B',
 'YER103W': 'SSA4',
 'YER104W': 'RTT105',
 'YER105C': 'NUP157',
 'YER106W': 'MAM1',
 'YER107C': 'GLE2',
 'YER109C': 'FLO8',
 'YER110C': 'KAP123',
 'YER111C': 'SWI4',
 'YER112W': 'LSM4',
 'YER113C': 'TMN3',
 'YER114C': 'BOI2',
 'YER115C': 'SPR6',
 'YER116C': 'SLX8',
 'YER117W': 'RPL23B',
 'YER118C': 'SHO1',
 'YER119C': 'AVT6',
 'YER120W': 'SCS2',
 'YER121W': nan,
 'YER122C': 'GLO3',
 'YER123W': 'YCK3',
 'YER124C': 'DSE1',
 'YER125W': 'RSP5',
 'YER126C': 'NSA2',
 'YER127W': 'LCP5',
 'YER128W': 'VFA1',
 'YER129W': 'SAK1',
 'YER130C': 'COM2',
 'YER131W': 'RPS26B',
 'YER132C': 'PMD1',
 'YER133W': 'GLC7',
 'YER134C': nan,
 'YER135C': nan,
 'YER136W': 'GDI1',
 'YER137C': nan,
 'YER139C': 'RTR1',
 'YER140W': 'EMP65',
 'YER141W': 'COX15',
 'YER142C': 'MAG1',
 'YER143W': 'DDI1',
 'YER144C': 'UBP5',
 'YER145C': 'FTR1',
 'YER146W': 'LSM5',
 'YER147C': 'SCC4',
 'YER148W': 'SPT15',
 'YER149C': 'PEA2',
 'YER150W': 'SPI1',
 'YER151C': 'UBP3',
 'YER152C': nan,
 'YER153C': 'PET122',
 'YER154W': 'OXA1',
 'YER155C': 'BEM2',
 'YER156C': 'MYG1',
 'YER157W': 'COG3',
 'YER158C': nan,
 'YER159C': 'BUR6',
 'YER161C': 'SPT2',
 'YER162C': 'RAD4',
 'YER163C': 'GCG1',
 'YER164W': 'CHD1',
 'YER165W': 'PAB1',
 'YER166W': 'DNF1',
 'YER167W': 'BCK2',
 'YER168C': 'CCA1',
 'YER169W': 'RPH1',
 'YER170W': 'ADK2',
 'YER171W': 'RAD3',
 'YER172C': 'BRR2',
 'YER173W': 'RAD24',
 'YER174C': 'GRX4',
 'YER175C': 'TMT1',
 'YER176W': 'ECM32',
 'YER177W': 'BMH1',
 'YER178W': 'PDA1',
 'YER179W': 'DMC1',
 'YER180C': 'ISC10',
 'YER181C': nan,
 'YER182W': 'FMP10',
 'YER183C': 'FAU1',
 'YER184C': 'TOG1',
 'YER185W': 'PUG1',
 'YER186C': nan,
 'YER187W': nan,
 'YER188W': nan,
 'YER189W': nan,
 'YER190W': 'YRF1-2',
 'YHL001W': 'RPL14B',
 'YHL002W': 'HSE1',
 'YHL003C': 'LAG1',
 'YHL004W': 'MRP4',
 'YHL005C': nan,
 'YHL006C': 'SHU1',
 'YHL007C': 'STE20',
 'YHL008C': nan,
 'YHL009C': 'YAP3',
 'YHL010C': 'ETP1',
 'YHL011C': 'PRS3',
 'YHL012W': nan,
 'YHL013C': 'OTU2',
 'YHL014C': 'YLF2',
 'YHL015W': 'RPS20',
 'YHL016C': 'DUR3',
 'YHL017W': nan,
 'YHL018W': 'MCO14',
 'YHL019C': 'APM2',
 'YHL020C': 'OPI1',
 'YHL021C': 'AIM17',
 'YHL022C': 'SPO11',
 'YHL023C': 'NPR3',
 'YHL024W': 'RIM4',
 'YHL025W': 'SNF6',
 'YHL026C': nan,
 'YHL027W': 'RIM101',
 'YHL028W': 'WSC4',
 'YHL029C': 'OCA5',
 'YHL030W': 'ECM29',
 'YHL031C': 'GOS1',
 'YHL032C': 'GUT1',
 'YHL033C': 'RPL8A',
 'YHL034C': 'SBP1',
 'YHL035C': 'VMR1',
 ...}

In [74]:
#correct gene names are in the description after GN=, including slashes
list_ZZ = dict(zip(df['description'].str.extract(r'GN=([\w-]+)')[0], df['duplicate_identity']))

In [192]:
#reverses order of dictionary (flip to common: systematic)
common_to_systematic = {v: k for k, v in gene_mapping.items()}

result = []
for gene, aa in list_ZZ.items():
    if gene in common_to_systematic:
        systematic = common_to_systematic[gene]
        common = gene
    elif gene in gene_mapping:
        systematic = gene
        common = np.nan
    else:
        systematic = np.nan
        common = np.nan
    result.append({'systematic_name': systematic, 'common_name': gene, 'amino_acid': aa})
    #captures genes (3) that didn't have a match in gene_mapping for common name 

df_result = pd.DataFrame(result)

In [193]:
merged = df_result.merge(df_all_new, left_on='systematic_name', right_on='Transcript_ID')
merged

,systematic_name,common_name,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon
0,YKL180W,RPL17A,AA,XI,RPL17A,YKL180W,+,110117,110138,ATTGCTGCTTAAATAGAAGAT,TAA,A,ATA
1,YBR115C,LYS2,AA,II,LYS2,YBR115C,-,469738,469759,GCAGCAGCTTAAGGTTGAGCA,TAA,G,GGT
2,YOR341W,RPA190,AA,XV,RPA190,YOR341W,+,965969,965990,AATGCGGCTTAGAAGCAGGCA,TAG,A,AAG
3,YGR144W,THI4,AA,VII,THI4,YGR144W,+,781367,781388,TTTGCTGCTTAGGCTTTTAAT,TAG,G,GCT
4,YDR519W,FPR2,AA,IV,FPR2,YDR519W,+,1480820,1480841,TCAGCCGCCTAGGTAAATTGG,TAG,G,GTA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,YDR105C,TMS1,YY,IV,TMS1,YDR105C,-,665339,665360,AATTACTATTAAATAGACTAA,TAA,A,ATA
553,YFR009W-A,YFR009W-A,YY,VI,unknown,YFR009W-A,+,164120,164141,ACCTATTATTGAAAGATGTTA,TGA,A,AAG
554,YKR032W,YKR032W,YY,XI,unknown,YKR032W,+,506819,506840,TTGTATTACTGAGCGGGATAT,TGA,G,GCG
555,YNL146C-A,YNL146C-A,YY,XIV,unknown,YNL146C-A,-,351376,351397,TTATATTATTAAACCTATTTT,TAA,A,ACC
556,YDR003W-A,YDR003W-A,YY,IV,unknown,YDR003W-A,+,454892,454913,ACATACTATTGATTTAGGTTT,TGA,T,TTT

In [194]:
#these genes didn't have a match for their annotated common name
missing = df_result[~df_result['systematic_name'].isin(merged['systematic_name'])]
print(missing)
#look up manually and add systematic name

    systematic_name common_name amino_acid
12              NaN        BSC2         AA
488             NaN        MDN1         SS
504             NaN        MCP2         SS

In [195]:
new_rows = pd.DataFrame([
    {'common_name': 'BSC2', 'systematic_name': 'YDR275W', 'amino_acid' : 'AA'},
    {'common_name': 'MDN1', 'systematic_name': 'YLR106C', 'amino_acid' : 'SS'},
    {'common_name': 'MCP2', 'systematic_name': 'YLR253W', 'amino_acid' : 'SS'}
])

merged = pd.concat([merged, new_rows], ignore_index=True)
merged

,systematic_name,common_name,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon
0,YKL180W,RPL17A,AA,XI,RPL17A,YKL180W,+,110117.0,110138.0,ATTGCTGCTTAAATAGAAGAT,TAA,A,ATA
1,YBR115C,LYS2,AA,II,LYS2,YBR115C,-,469738.0,469759.0,GCAGCAGCTTAAGGTTGAGCA,TAA,G,GGT
2,YOR341W,RPA190,AA,XV,RPA190,YOR341W,+,965969.0,965990.0,AATGCGGCTTAGAAGCAGGCA,TAG,A,AAG
3,YGR144W,THI4,AA,VII,THI4,YGR144W,+,781367.0,781388.0,TTTGCTGCTTAGGCTTTTAAT,TAG,G,GCT
4,YDR519W,FPR2,AA,IV,FPR2,YDR519W,+,1480820.0,1480841.0,TCAGCCGCCTAGGTAAATTGG,TAG,G,GTA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,YNL146C-A,YNL146C-A,YY,XIV,unknown,YNL146C-A,-,351376.0,351397.0,TTATATTATTAAACCTATTTT,TAA,A,ACC
556,YDR003W-A,YDR003W-A,YY,IV,unknown,YDR003W-A,+,454892.0,454913.0,ACATACTATTGATTTAGGTTT,TGA,T,TTT
557,YDR275W,BSC2,AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,YLR106C,MDN1,SS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,YLR253W,MCP2,SS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [196]:
#remove columns so I can merge again with three additional missing genes
merged_clean = merged[['systematic_name', 'common_name', 'amino_acid']]
merged_clean

    systematic_name common_name amino_acid
0           YKL180W      RPL17A         AA
1           YBR115C        LYS2         AA
2           YOR341W      RPA190         AA
3           YGR144W        THI4         AA
4           YDR519W        FPR2         AA
..              ...         ...        ...
555       YNL146C-A   YNL146C-A         YY
556       YDR003W-A   YDR003W-A         YY
557         YDR275W        BSC2         AA
558         YLR106C        MDN1         SS
559         YLR253W        MCP2         SS

[560 rows x 3 columns]

In [197]:
new_merged = merged_clean.merge(df_all_new, left_on='systematic_name', right_on='Transcript_ID', how='left')
new_merged

,systematic_name,common_name,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon
0,YKL180W,RPL17A,AA,XI,RPL17A,YKL180W,+,110117,110138,ATTGCTGCTTAAATAGAAGAT,TAA,A,ATA
1,YBR115C,LYS2,AA,II,LYS2,YBR115C,-,469738,469759,GCAGCAGCTTAAGGTTGAGCA,TAA,G,GGT
2,YOR341W,RPA190,AA,XV,RPA190,YOR341W,+,965969,965990,AATGCGGCTTAGAAGCAGGCA,TAG,A,AAG
3,YGR144W,THI4,AA,VII,THI4,YGR144W,+,781367,781388,TTTGCTGCTTAGGCTTTTAAT,TAG,G,GCT
4,YDR519W,FPR2,AA,IV,FPR2,YDR519W,+,1480820,1480841,TCAGCCGCCTAGGTAAATTGG,TAG,G,GTA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,YNL146C-A,YNL146C-A,YY,XIV,unknown,YNL146C-A,-,351376,351397,TTATATTATTAAACCTATTTT,TAA,A,ACC
556,YDR003W-A,YDR003W-A,YY,IV,unknown,YDR003W-A,+,454892,454913,ACATACTATTGATTTAGGTTT,TGA,T,TTT
557,YDR275W,BSC2,AA,IV,BSC2,YDR275W,+,1012947,1012968,AAAGCTGCTTAAATTGATAAT,TAA,A,ATT
558,YLR106C,MDN1,SS,XII,MDN1,YLR106C,-,348996,349017,GCATCCAGCTAAGTATATCGT,TAA,G,GTA
559,YLR253W,MCP2,SS,XII,MCP2,YLR253W,+,644324,644345,TTGTCATCTTAAATCGTTAGC,TAA,A,ATC

In [198]:
#find mito genes
new_merged[new_merged['systematic_name'].str.startswith('Q')]

,systematic_name,common_name,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon
308,Q0297,Q0297,KK,Mito,unknown,Q0297,+,85697,85718,AAAAAAAAGTAATATATATAT,TAA,T,TAT
373,Q0120,BI4,NN,Mito,BI4,Q0120,+,42239,42260,AATAATAATTAAATTTTCTCC,TAA,A,ATT

In [199]:
new_merged = new_merged[~new_merged['systematic_name'].isin(['Q0297', 'Q0120'])] #drop mito genes

In [200]:
new_merged[new_merged['systematic_name'].str.startswith('Q')] #check if mito genes still there
new_merged

,systematic_name,common_name,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon
0,YKL180W,RPL17A,AA,XI,RPL17A,YKL180W,+,110117,110138,ATTGCTGCTTAAATAGAAGAT,TAA,A,ATA
1,YBR115C,LYS2,AA,II,LYS2,YBR115C,-,469738,469759,GCAGCAGCTTAAGGTTGAGCA,TAA,G,GGT
2,YOR341W,RPA190,AA,XV,RPA190,YOR341W,+,965969,965990,AATGCGGCTTAGAAGCAGGCA,TAG,A,AAG
3,YGR144W,THI4,AA,VII,THI4,YGR144W,+,781367,781388,TTTGCTGCTTAGGCTTTTAAT,TAG,G,GCT
4,YDR519W,FPR2,AA,IV,FPR2,YDR519W,+,1480820,1480841,TCAGCCGCCTAGGTAAATTGG,TAG,G,GTA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,YNL146C-A,YNL146C-A,YY,XIV,unknown,YNL146C-A,-,351376,351397,TTATATTATTAAACCTATTTT,TAA,A,ACC
556,YDR003W-A,YDR003W-A,YY,IV,unknown,YDR003W-A,+,454892,454913,ACATACTATTGATTTAGGTTT,TGA,T,TTT
557,YDR275W,BSC2,AA,IV,BSC2,YDR275W,+,1012947,1012968,AAAGCTGCTTAAATTGATAAT,TAA,A,ATT
558,YLR106C,MDN1,SS,XII,MDN1,YLR106C,-,348996,349017,GCATCCAGCTAAGTATATCGT,TAA,G,GTA
559,YLR253W,MCP2,SS,XII,MCP2,YLR253W,+,644324,644345,TTGTCATCTTAAATCGTTAGC,TAA,A,ATC

In [201]:
new_merged = new_merged.drop(columns=['systematic_name', 'common_name'])
new_merged

,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon
0,AA,XI,RPL17A,YKL180W,+,110117,110138,ATTGCTGCTTAAATAGAAGAT,TAA,A,ATA
1,AA,II,LYS2,YBR115C,-,469738,469759,GCAGCAGCTTAAGGTTGAGCA,TAA,G,GGT
2,AA,XV,RPA190,YOR341W,+,965969,965990,AATGCGGCTTAGAAGCAGGCA,TAG,A,AAG
3,AA,VII,THI4,YGR144W,+,781367,781388,TTTGCTGCTTAGGCTTTTAAT,TAG,G,GCT
4,AA,IV,FPR2,YDR519W,+,1480820,1480841,TCAGCCGCCTAGGTAAATTGG,TAG,G,GTA
...,...,...,...,...,...,...,...,...,...,...,...
555,YY,XIV,unknown,YNL146C-A,-,351376,351397,TTATATTATTAAACCTATTTT,TAA,A,ACC
556,YY,IV,unknown,YDR003W-A,+,454892,454913,ACATACTATTGATTTAGGTTT,TGA,T,TTT
557,AA,IV,BSC2,YDR275W,+,1012947,1012968,AAAGCTGCTTAAATTGATAAT,TAA,A,ATT
558,SS,XII,MDN1,YLR106C,-,348996,349017,GCATCCAGCTAAGTATATCGT,TAA,G,GTA
559,SS,XII,MCP2,YLR253W,+,644324,644345,TTGTCATCTTAAATCGTTAGC,TAA,A,ATC

In [202]:
new_merged['4-stop signal']=new_merged['Stop Codon'] + new_merged['+4 nucleotide']
new_merged

,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon,4-stop signal
0,AA,XI,RPL17A,YKL180W,+,110117,110138,ATTGCTGCTTAAATAGAAGAT,TAA,A,ATA,TAAA
1,AA,II,LYS2,YBR115C,-,469738,469759,GCAGCAGCTTAAGGTTGAGCA,TAA,G,GGT,TAAG
2,AA,XV,RPA190,YOR341W,+,965969,965990,AATGCGGCTTAGAAGCAGGCA,TAG,A,AAG,TAGA
3,AA,VII,THI4,YGR144W,+,781367,781388,TTTGCTGCTTAGGCTTTTAAT,TAG,G,GCT,TAGG
4,AA,IV,FPR2,YDR519W,+,1480820,1480841,TCAGCCGCCTAGGTAAATTGG,TAG,G,GTA,TAGG
...,...,...,...,...,...,...,...,...,...,...,...,...
555,YY,XIV,unknown,YNL146C-A,-,351376,351397,TTATATTATTAAACCTATTTT,TAA,A,ACC,TAAA
556,YY,IV,unknown,YDR003W-A,+,454892,454913,ACATACTATTGATTTAGGTTT,TGA,T,TTT,TGAT
557,AA,IV,BSC2,YDR275W,+,1012947,1012968,AAAGCTGCTTAAATTGATAAT,TAA,A,ATT,TAAA
558,SS,XII,MDN1,YLR106C,-,348996,349017,GCATCCAGCTAAGTATATCGT,TAA,G,GTA,TAAG
559,SS,XII,MCP2,YLR253W,+,644324,644345,TTGTCATCTTAAATCGTTAGC,TAA,A,ATC,TAAA

In [210]:
scores = pd.read_csv('stopcodonscores.csv') #load scoring file based on data from https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1009538
score_dict = dict(zip(scores['Stop'], scores['Score'])) #saving scores to dictionary
new_merged['Score'] = new_merged['4-stop signal'].map(score_dict) #mapping scores to each 4-stop signal in dataset
new_merged

,amino_acid,Chromosome,Gene_name,Transcript_ID,Strand,Start,End,Sequence,Stop Codon,+4 nucleotide,3UTR codon,4-stop signal,Score
0,AA,XI,RPL17A,YKL180W,+,110117,110138,ATTGCTGCTTAAATAGAAGAT,TAA,A,ATA,TAAA,11
1,AA,II,LYS2,YBR115C,-,469738,469759,GCAGCAGCTTAAGGTTGAGCA,TAA,G,GGT,TAAG,12
2,AA,XV,RPA190,YOR341W,+,965969,965990,AATGCGGCTTAGAAGCAGGCA,TAG,A,AAG,TAGA,7
3,AA,VII,THI4,YGR144W,+,781367,781388,TTTGCTGCTTAGGCTTTTAAT,TAG,G,GCT,TAGG,8
4,AA,IV,FPR2,YDR519W,+,1480820,1480841,TCAGCCGCCTAGGTAAATTGG,TAG,G,GTA,TAGG,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,YY,XIV,unknown,YNL146C-A,-,351376,351397,TTATATTATTAAACCTATTTT,TAA,A,ACC,TAAA,11
556,YY,IV,unknown,YDR003W-A,+,454892,454913,ACATACTATTGATTTAGGTTT,TGA,T,TTT,TGAT,2
557,AA,IV,BSC2,YDR275W,+,1012947,1012968,AAAGCTGCTTAAATTGATAAT,TAA,A,ATT,TAAA,11
558,SS,XII,MDN1,YLR106C,-,348996,349017,GCATCCAGCTAAGTATATCGT,TAA,G,GTA,TAAG,12
559,SS,XII,MCP2,YLR253W,+,644324,644345,TTGTCATCTTAAATCGTTAGC,TAA,A,ATC,TAAA,11

In [240]:
#new_merged = new_merged[['Gene_name', 'Transcript_ID','Chromosome', 'Strand','Start','End','Sequence', 'amino_acid',
                         #'Stop Codon', '+4 nucleotide', '3UTR codon','4-stop signal', 'Score']]
new_merged = new_merged.rename(columns={'+4 nucleotide':'+4 Nucleotide'})

new_merged.to_csv('FilteredDuplicateEndings_Final.csv', index=False)

In [225]:
#make score lists of all QQ and YY endings
list_all_QQ = new_merged[new_merged['amino_acid'] != 'QQ']['Score'].tolist()
list_QQ = new_merged[new_merged['amino_acid'] == 'QQ']['Score'].tolist()

list_all_YY = new_merged[new_merged['amino_acid'] != 'YY']['Score'].tolist()
list_YY = new_merged[new_merged['amino_acid'] == 'YY']['Score'].tolist()

In [243]:
from scipy.stats import mannwhitneyu

stat, pvalue = mannwhitneyu(list_QQ, list_all_QQ, alternative='two-sided')
print(f"U statistic: {stat}, p-value: {pvalue}")

U statistic: 7794.5, p-value: 0.0005934297115955239

In [241]:
from scipy.stats import mannwhitneyu

stat, pvalue = mannwhitneyu(list_YY, list_all_YY, alternative='two-sided')
print(f"U statistic: {stat}, p-value: {pvalue}")

U statistic: 3033.0, p-value: 0.9635787044155879